### ISSUE TITLE
createEvent should return the result of saveStatement, not the event. 

### ISSUE THREAD

**Issue by garemoko** [LearningLocker/xAPI-Recipe-Emitter#26]
This would make it easier to debug failed statements.

**Comment by garemoko** [comment]
actually, it'd be useful to have both the event and the result.

**Comment by ryansmith94** [comment]
+1

**Comment by garemoko** [comment]
@ryansmith94 The other side of me things it's quite neat to return the event to maintain the pattern of the other components. Is there any way to call the store's error_log_value function from the emitter? I tried making it public but still can't find it.

**Comment by ryansmith94** [comment]
Yeah I agree. No there isn't currently. You'd have to pass the function in, however your tests should be good enough to not require this.

**Comment by ryansmith94** [comment]
What's the status here @garemoko @jlowe64?

**Comment by garemoko** [comment]
@ryansmith94 I haven't done anything to address this. I don't think it's as simple as it looks and needs some design thought before/when it's implemented. 

Just so you know, I'm not planning any more work on this plugin myself for a little while, partly due to some other priorities but also because I'm happy with where we've got to for now!

**Comment by ryansmith94** [comment]
No worries @garemoko, thanks for the response and all of your contributions :+1:

**Comment by garemoko** [comment]
This is fixed: https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/src/Repository.php#L23-L28
