### ISSUE TITLE
Moodle specific activity types a good idea?

### ISSUE THREAD

**Issue by garemoko** [LearningLocker/xAPI-Recipe-Emitter#28]
For discussion. 

I'm designing some statements for another LMS. I think it makes sense to use the same activity type for for all course LMSs, but I'm reticent to use "http://lrs.learninglocker.net/define/type/moodle/course" because that seems Moodle specific. 

Right now I'm tempted to coin another identifier for this other LMS, which would be something like  http://id.tincanapi.com/activitytype/lms-course

Thoughts?

**Comment by ryansmith94** [comment]
I agree that another platform should have its own type and not a Moodle specific one. I'm not sure if you're already asking this question, but if not, I'd like to know if we think we should change the type to be something generic for all LMS courses.

**Comment by garemoko** [comment]
@ryansmith94 yeh, I'm proposing using a more generic identifier, especially as the emitter isn't supposed to be Moodle specific.

**Comment by ryansmith94** [comment]
I think the identifier actually comes from the translator.

**Comment by jlowe64** [comment]
@garemoko are we talking about just changing the documentation here to reflect something less moodle specific?

**Comment by garemoko** [comment]
@jlowe64 I'm talking about the actual identifier used in statements, which is currently "http://lrs.learninglocker.net/define/type/moodle/course" (I'm sure there are others, course is an example that's affecting me right now).

This could be changed to "http://lrs.learninglocker.net/define/type/course" or even "http://id.tincanapi.com/activitytype/lms-course" to make it non-lrs specific. 

Note: If anybody is already using the plugins, changing the identifiers is going to cause them problems. Given that the 1.0.0 version was 21 days ago, that's an argument not to change anything. On the other hand, better to do it now than later when the plugin has more adoption.

**Comment by ryansmith94** [comment]
If that identifier is defined in the Translator as I suspect, then it might be fine.

**Comment by jlowe64** [comment]
I think if it's in Translator, it should stay, since that's moodle specific. However, the documentation here probably should reflect something more generic, since this repo isn't Moodle specific.

**Comment by jlowe64** [comment]
@ryansmith94 is Translator moodle specific? I forget which are being used for other sources. I know Expander is definitely moodle specific.

**Comment by ryansmith94** [comment]
Translator is Moodle and xAPI specific, it ties the two together. So "anything goes" in there to a certain extent.

**Comment by jlowe64** [comment]
I think it could stay as is, then. I do think the docs here might need to be less moodle specific, though.

**Comment by ryansmith94** [comment]
Ok, would be good to make the docs less specific.

**Comment by jlowe64** [comment]
@garemoko are you wanting to use `http://id.tincanapi.com/activitytype/lms-course` in the documentation? I followed the link and nothing existed. An update on this would be very appreciative!

**Comment by garemoko** [comment]
I was propsoing http://id.tincanapi.com/activitytype/lms-course and it's waiting to be reviewed in Registry, but actually I think in the meantime JISC may have coined their own term.

**Comment by jlowe64** [comment]
@garemoko Thanks buddy. I'll just put this particular bit on hold until that's been confirmed. If you wouldn't mind, if something is finalized could you report back? I'd really appreciate it. :)

**Comment by davidpesce** [comment]
@garemoko any updates/conclusions on this? I'm trying to get things cleaned up in here.

**Comment by garemoko** [comment]
http://id.tincanapi.com/activitytype/lms-course is still not in the registry and actually, looking back over my email I don't see the submission receipt (though it's very possible I deleted it). 

@brianjmiller do you have http://id.tincanapi.com/activitytype/lms-course as a pending submission in the registry?

**Comment by garemoko** [comment]
In the meantime, I have used http://id.tincanapi.com/activitytype/lms-course in statements.

**Comment by davidpesce** [comment]
Sounds good. I'll proceed with http://id.tincanapi.com/activitytype/lms-course

@garemoko if there are any PRs or issues on any of the four repos that you want to weigh in on, that'd be awesome! The plan is to get each one up to date with PRs issues and then get them into a single repository.

**Comment by garemoko** [comment]
@davidpesce its been a while since I looked at it, so I think I'll need to rely on you to ping me on PRs as needed. The one PR from me was ready to merge at the time. Looks like it's conflicting now but hopefully that's an easy thing to fix.

**Comment by davidpesce** [comment]
Yeah, I think that's from the last merge. I was doing a bunch of work in those files.

I believe I'm going to attack the SCORM-event PRs next. I'll tag you on each one to get your input.

**Comment by davidpesce** [comment]
Migrating to main repository.
